name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  proxied:
    path: ../

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^4.0.0
  test: ^1.24.0
